language: php
php:
  - 5.6

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - composer require --no-update satooshi/php-coveralls '~1.0'

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls

sudo: false

