language: php
php:
  - 7.1

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - export SYMFONY_ENV=test
  - composer require --no-update satooshi/php-coveralls '~1.0'
  - composer update
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php ./vendor/satooshi/php-coveralls/bin/coveralls -v

sudo: false

