imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    channels: ['weather']
    handlers:
        weather:
            level:    debug
            type:     stream
            path: '%kernel.logs_dir%/weather.log'
            channels: ['weather']

easy_admin:
    list:
        max_results: 100
    entities:
        MonitoredAirports:
            class: AppBundle\Entity\MonitoredAirports
            label: "Monitored Airports"
            list:
                max_results: 100
                actions:
                  - { name: 'new', label: 'New Monitored Airport'}
                fields:
                    - { property: 'airportData', label: 'Airport' }
                    - { property: 'activeWinter', type: 'toggle', label: 'Act. W'}
                    - { property: 'alternateWinter', type: 'toggle', label: 'Altn. W'}
                    - { property: 'activeSummer', type: 'toggle', label: 'Act. S'}
                    - { property: 'alternateSummer', type: 'toggle', label: 'Altn. S'}
                    - { property: 'midWarningVis', label: 'Vis. Y'}
                    - { property: 'midWarningCeiling', label: 'Ceil. Y'}
                    - { property: 'midWarningWind', label: 'Wind. Y'}
                    - { property: 'highWarningVis', label: 'Vis. R'}
                    - { property: 'highWarningCeiling', label: 'Ceil. R'}
                    - { property: 'highWarningWind', label: 'Wind. R'}
            form:
                fields:
                    - { property: 'airportData', label: 'Airport' }
                    - { property: 'activeWinter', label: 'Act. W'}
                    - { property: 'alternateWinter', label: 'Altn. W'}
                    - { property: 'activeSummer', label: 'Act. S'}
                    - { property: 'alternateSummer', label: 'Altn. S'}
                    - { property: 'midWarningVis', label: 'Vis. Y'}
                    - { property: 'midWarningCeiling', label: 'Ceil. Y'}
                    - { property: 'midWarningWind', label: 'Wind. Y'}
                    - { property: 'highWarningVis', label: 'Vis. R'}
                    - { property: 'highWarningCeiling', label: 'Ceil. R'}
                    - { property: 'highWarningWind', label: 'Wind. R'}
        AirportsMasterData:
            class: AppBundle\Entity\AirportsMasterData
            label: "Airport Master Data"
