imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # Enter your server here, no trailing slash, i.e. - http://server.weather.aero
    weather-server: http://server.lidousers.com

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: WXSESS
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        server_version: 5.6

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    channels: ['weather']
    handlers:
        weather:
            level:    info
            type:     rotating_file
            path: '%kernel.logs_dir%/weather.log'
            channels: ['weather']

easy_admin:
    site_name: 'Airport Weather Monitor'
    design:
      #brand_color: '#D8B37B'
      color_scheme: 'light'
      form_theme: 'vertical'
    list:
        max_results: 100
    entities:
        MonitoredAirport:
            class: AppBundle\Entity\MonitoredAirport
            label: "Monitored Airports"
            edit:
                title: "Edit Monitored Airport"
            new:
                title: "New Monitored Airport"
            list:
                title: "Monitored Airports"
                max_results: 500
                actions:
                  - { name: 'new', label: 'New Monitored Airport'}
                fields:
                    - { property: 'airportData', label: 'Airport' }
                    - { property: 'activeWinter', type: 'toggle', label: 'Act. W'}
                    - { property: 'alternateWinter', type: 'toggle', label: 'Altn. W'}
                    - { property: 'activeSummer', type: 'toggle', label: 'Act. S'}
                    - { property: 'alternateSummer', type: 'toggle', label: 'Altn. S'}
                    - { property: 'midWarningVis', label: 'Vis. Y', css_class: text-right}
                    - { property: 'midWarningCeiling', label: 'Ceil. Y', css_class: text-right}
                    - { property: 'midWarningWind', label: 'Wind. Y', css_class: text-right}
                    - { property: 'highWarningVis', label: 'Vis. R', css_class: text-right}
                    - { property: 'highWarningCeiling', label: 'Ceil. R', css_class: text-right}
                    - { property: 'highWarningWind', label: 'Wind. R', css_class: text-right}
            form:
                title: "Edit Monitored Airport"
                fields:
                    - { type: 'group', label: 'Airport', css_class: 'col-sm-4' }
                    - { property: 'airportData', label: 'Airport' }
                    - { type: 'group', label: 'Winter', css_class: 'col-sm-4' }
                    - { property: 'activeWinter', label: 'Active monitoring during Winter'}
                    - { property: 'alternateWinter', label: 'Alternate during Winter'}
                    - { type: 'group', label: 'Summer', css_class: 'col-sm-4' }
                    - { property: 'activeSummer', label: 'Active monitoring during Summer'}
                    - { property: 'alternateSummer', label: 'Alternate during Summer'}
                    - { type: 'group', label: 'Normal Minimas', css_class: 'col-sm-6' }
                    - { property: 'midWarningVis', label: 'Visibility Yellow'}
                    - { property: 'midWarningCeiling', label: 'Ceiling Yellow'}
                    - { property: 'midWarningWind', label: 'Wind Yellow'}
                    - { property: 'highWarningVis', label: 'Visibility Red'}
                    - { property: 'highWarningCeiling', label: 'Ceiling Red'}
                    - { property: 'highWarningWind', label: 'Wind Red'}
                    - { type: 'group', label: 'Alternate Minimas', css_class: 'col-sm-6' }
                    - { property: 'midWarningVisAlt', label: 'Visibility Yellow'}
                    - { property: 'midWarningCeilingAlt', label: 'Ceilinig Yellow'}
                    - { property: 'midWarningWindAlt', label: 'Wind Yellow'}
                    - { property: 'highWarningVisAlt', label: 'Visibility Red'}
                    - { property: 'highWarningCeilingAlt', label: 'Ceilinig Red'}
                    - { property: 'highWarningWindAlt', label: 'Wind Red'}
        MonitoredPhenomenons:
            class: AppBundle\Entity\MonitoredPhenomenons
            disabled_actions: ['new', 'delete']
            label: "Phenomenons"
            list:
              title: "Monitored Phenomenons"
              fields:
                - { property: 'warning_level', label: 'Warning Level', template: 'phenomenon.html.twig'}
                - { property: 'phenomenons', label: 'Phenomenons'}
            edit:
              title: "Edit Monitored Phenomenon"
              fields:
                - {property: 'phenomenons', label: 'Phenomenons'}
        AirportsMasterData:
            class: AppBundle\Entity\AirportsMasterData
            label: "Airports Master Data"
            list:
              sort: ['airportIcao', 'ASC']
              title: "Airports Master Data"
              fields:
                - { property: 'airport_icao', label: "ICAO Code"}
                - { property: 'lat', label: "Latitude"}
                - { property: 'lon', label: "Longitude"}
              actions:
                - { name: 'new', label: 'New Master Airport Data'}
            edit:
              title: "Edit Airport Master Data"
            new:
              title: "New Airport Master Data"
            form:
              fields:
                - { property: 'airport_icao', label: "Airport ICAO code", type: "text"}
                - { property: 'lat', label: "Latitude"}
                - { property: 'lon', label: "Longitude"}

